version: 2
jobs:
  lint:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Check formatting
          command: ./scripts/rustfmt.sh
  build:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Build concatenated lock file for caching
          command: find . -name "Cargo.lock" -not -path "*/target/*" | xargs cat > concatenated.lock
      - run:
          name: Store rust version in an environment var for cache key
          command: rustc --version > rust.version
      - restore_cache:
          keys:
            - release-cache-{{ checksum "./concatenated.lock" }}-{{ checksum "./rust.version" }}
            - release-cache-{{ checksum "./Cargo.lock" }}-{{ checksum "./rust.version" }}
            - release-cache-{{ checksum "./rust.version" }}
      - run:
          name: Build release
          command: cargo build -j 1 --release
          no_output_timeout: 4h
      - save_cache:
          key: release-cache-{{ checksum "./concatenated.lock" }}-{{ checksum "./rust.version" }}
          paths:
            - "~/.cargo"
            - "./target"
            - "./pallets/runtime/target"
            - "./pallets/runtime/wasm/target"
      - save_cache:
          key: release-cache-{{ checksum "./Cargo.lock" }}-{{ checksum "./rust.version" }}
          paths:
            - "~/.cargo"
            - "./target"
            - "./pallets/runtime/target"
            - "./pallets/runtime/wasm/target"
      - save_cache:
          key: release-cache-{{ checksum "./rust.version" }}
          paths:
            - "~/.cargo"
            - "./target"
            - "./pallets/runtime/target"
            - "./pallets/runtime/wasm/target"
  test:
    docker:
      - image: maxsam4/rust
    environment:
      VERBOSE: "1"
    steps:
      - checkout
      - run:
          name: Build concatenated lock file for caching
          command: find . -name "Cargo.lock" -not -path "*/target/*" | xargs cat > concatenated.lock
      - run:
          name: Store rust version in a file for cache key
          command: rustc --version > rust.version
      - restore_cache:
          keys:
            - debug-cache-{{ checksum "./concatenated.lock" }}-{{ checksum "./rust.version" }}
            - debug-cache-{{ checksum "./pallets/runtime/Cargo.lock" }}-{{ checksum "./rust.version" }}
            - debug-cache-{{ checksum "./rust.version" }}
      - run:
          name: runtime tests
          command: cargo test
          working_directory: ./pallets/runtime
          no_output_timeout: 60m
      - save_cache:
          key: debug-cache-{{ checksum "./concatenated.lock" }}-{{ checksum "./rust.version" }}
          paths:
            - "~/.cargo"
            - "./target"
            - "./pallets/runtime/target"
            - "./pallets/runtime/wasm/target"
      - save_cache:
          key: release-cache-{{ checksum "./pallets/runtime/Cargo.lock" }}-{{ checksum "./rust.version" }}
          paths:
            - "~/.cargo"
            - "./target"
            - "./pallets/runtime/target"
            - "./pallets/runtime/wasm/target"
      - save_cache:
          key: debug-cache-{{ checksum "./rust.version" }}
          paths:
            - "~/.cargo"
            - "./target"
            - "./pallets/runtime/target"
            - "./pallets/runtime/wasm/target"
workflows:
  version: 2
  commit:
    jobs:
      - lint
      - build
      - test
  daily-builds:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
