[package]
name = "polymesh-runtime-common"
version = "1.0.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-common-utilities = { package = "polymesh-common-utilities", path = "../../common", default-features = false }
polymesh-primitives = { package = "polymesh-primitives", path = "../../../primitives", default-features = false }
pallet-protocol-fee = { package = "pallet-protocol-fee", path = "../../protocol-fee", default-features = false }
pallet-identity = { package = "pallet-identity", path = "../../identity", default-features = false  }
pallet-balances = { package = "pallet-balances", path = "../../balances", default-features = false  }
pallet-transaction-payment = { package = "pallet-transaction-payment", path = "../../transaction-payment", default-features = false  }
pallet-committee = { package = "pallet-committee", path = "../../committee", default-features = false }
pallet-mips = { package = "pallet-mips", path = "../../mips", default-features = false }
pallet-group = { package = "pallet-group", path = "../../group", default-features = false}
pallet-multisig = { package = "pallet-multisig", path = "../../multisig", default-features = false}

chrono = { version = "0.4.11", default-features = false }
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true }
serde_json = { version = "1.0.48", default-features = false }

sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

pallet-contracts = { package = "pallet-contracts", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-timestamp = { package = "pallet-timestamp", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-treasury = { package = "pallet-treasury", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
pallet-authorship = { package = "pallet-authorship", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }
ink_primitives = { git = "https://github.com/paritytech/ink", package = "ink_primitives", default-features = false }
hex-literal = "0.2.1"

[dev-dependencies]
test-client = { package = "substrate-test-runtime-client", git = "https://github.com/paritytech/substrate", rev = "a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8" }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
	"serde_derive",
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"pallet-contracts/std",
	"pallet-timestamp/std",
	"pallet-treasury/std",
	"pallet-group/std",
	"pallet-mips/std",
	"pallet-committee/std",
	"pallet-balances/std",
	"pallet-identity/std",
	"pallet-multisig/std",
	"pallet-transaction-payment/std",
	"frame-support/std",
	"frame-system/std",
	"polymesh-common-utilities/std",
	"pallet-protocol-fee/std",
	"ink_primitives/std"
]
