[package]
name = "pallet-cdd-offchain-worker"
version = "0.1.0"
authors = ["Polymath Inc. <satyam@polymath.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.1.2", default-features = false, features = ["derive"] }
frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421" }
pallet-timestamp = { package = "pallet-timestamp", git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421" }
sp-offchain = { package = "sp-offchain", git = "https://github.com/paritytech/substrate", default-features = false, rev = "93569d0d1af7aa5eb67b9de8b58d7fffde63b421" }
polymesh-runtime-common = {pacakge = "polymesh-runtime-common", path = "../common", default-features = false}
pallet-staking = {package = "pallet-staking", path = "../staking", default-features = false }

[features]
equalize = []
default = ["std"]
no_std = []
only-staking = []
std = [ 
	"sp-offchain/std",
	"sp-runtime/std",
	"pallet-timestamp/std",
	"frame-support/std",
	"frame-system/std",
    "polymesh-runtime-common/std",
	"pallet-staking/std",
]