name: Publish docs

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        default: true
    - name: Build
      run: cargo docs --no-deps --release --verbose
    - name: Publish
      uses: cloudflare/wrangler-action@1.1.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
